---
- name: restart chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted

- name: reboot host
  ansible.builtin.reboot:
    reboot_timeout: 600
    pre_reboot_delay: 10
    post_reboot_delay: 30
    msg: "Reboot initiated by Ansible (SELinux change)"
