---
- name: Import check versions
  ansible.builtin.import_tasks: check.yml

- name: Prepare repositories
  ansible.builtin.import_tasks: prepare_repos.yml

- name: Resolve package versions
  ansible.builtin.import_tasks: resolve_packages.yml

- name: Import kubeadm and cri-o upgrade
  ansible.builtin.import_tasks: kubeadm-crio.yml

- name: Import kubelet and kubectl upgrade
  ansible.builtin.import_tasks: kubelet-kubectl.yml
