---
- name: "Prepare repos for target versions"
  block:
    - name: Ensure Kubernetes repo
      ansible.builtin.template:
        src: k8s.repo.j2
        dest: /etc/yum.repos.d/k8s.repo
        owner: root
        group: root
        mode: 0644
    - name: Ensure CRI-O repo
      ansible.builtin.template:
        src: cri-o.repo.j2
        dest: /etc/yum.repos.d/cri-o.repo
        owner: root
        group: root
        mode: 0644
    - name: Import Kubernetes GPG key
      ansible.builtin.rpm_key:
        key: "https://repo.seaspace.name:48443/core:/stable:/{{ k8s_repo_minor }}/rpm/repodata/repomd.xml.key"
        state: present
    - name: Import CRI-O GPG key
      ansible.builtin.rpm_key:
        key: "https://repo.seaspace.name:48443/repositories/isv:/cri-o:/stable:/{{ crio_repo_minor }}/rpm/repodata/repomd.xml.key"
        state: present
    - name: Clean DNF cache
      ansible.builtin.command: dnf clean all
      changed_when: false
    - name: Refresh DNF cache for enabled repos
      ansible.builtin.command: dnf makecache --enablerepo kubernetes,cri-o
      changed_when: false
  when: need_pkg_update