---
- name: Unhold packages (Debian)
  ansible.builtin.command: apt-mark unhold kubeadm kubelet kubectl cri-o
  when: ansible_os_family == 'Debian'

- name: Unhold packages (RedHat) - delete versionlock
  ansible.builtin.command: dnf versionlock delete kubeadm kubelet kubectl cri-o
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes
