user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    # Использование публичных DNS (Google и Cloudflare)
    # ipv6=off — критически важно, чтобы Nginx не пытался ходить по недоступным адресам
    # valid=300s — кэширование ответов DNS на 5 минут
    resolver 8.8.8.8 1.1.1.1 8.8.4.4 valid=300s ipv6=off;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    # Увеличиваем размер корзины хэша для имен серверов
    server_names_hash_bucket_size 64;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Подключаем наш прокси-конфиг
    include /etc/nginx/conf.d/*.conf;

    # Мы удалили блок server { listen 80 ... } отсюда,
    # так как он будет описан в отдельном файле для нашего домена.
}
