---
- name: "kubeadm and cri-o upgrade first master"
  become: yes
  gather_facts: yes
  hosts: masters[0]
  serial: 1
  tasks:
    - name: Check info version
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: check.yml
    - name: Prepare repositories
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: prepare_repos.yml
    - name: Resolve package versions
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: resolve_packages.yml
    - name: Upgrade kubeadm/cri-o on first master
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: kubeadm-crio.yml

- name: "kubeadm and cri-o upgrade other masters"
  become: yes
  gather_facts: yes
  hosts: masters[1:]
  serial: 1
  tasks:
    - name: Check info version
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: check.yml
    - name: Prepare repositories
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: prepare_repos.yml
    - name: Resolve package versions
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: resolve_packages.yml
    - name: Upgrade kubeadm/cri-o on other masters
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: kubeadm-crio.yml

- name: "upgrade kubelet and kubectl on masters"
  become: yes
  gather_facts: yes
  hosts: masters
  serial: 1
  tasks:
    - name: Check info version
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: check.yml
    - name: Prepare repositories
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: prepare_repos.yml
    - name: Resolve package versions
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: resolve_packages.yml
    - name: Upgrade kubelet and kubectl
      ansible.builtin.include_role:
        name: k8s_upgrade
        tasks_from: kubelet-kubectl.yml

- name: "upgrade worker nodes"
  become: yes
  gather_facts: yes
  hosts: workers
  serial: 1
  roles:
    - k8s_upgrade
